# Generated by Django 4.0.4 on 2022-06-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_price_product_schedule_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='home/static/images/no-img.jpg', upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='product',
            name='imageName',
            field=models.CharField(default='home/static/images/no-img.jpg', max_length=200),
        ),
    ]
