# Generated by Django 4.0.4 on 2022-06-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_image_product_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='home/static/images/no-img.jpg', upload_to='home'),
        ),
    ]
