# Generated by Django 4.0.4 on 2022-06-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_product_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/no-img.jpg', upload_to='home'),
        ),
    ]
